language: php

services:
  - mysql

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

before_install:
  # Turn off XDebug
  - phpenv config-rm xdebug.ini || return 0
  - mysql -e 'CREATE DATABASE datagridTest;'

install:
  - travis_retry composer install --no-progress --prefer-dist # Install dependencies

before_script:
  - mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql

script:
  - composer tests

jobs:
  include:
    - env: title="Lowest Dependencies 7.2"
      php: 7.2
      install:
        - travis_retry composer update --no-progress --prefer-dist --prefer-lowest
      script:
        - composer tests

    - stage: Quality Assurance
      php: 7.4
      script:
        - composer phpstan
        - composer phpcs

    - stage: Test Coverage
      if: branch = master AND type = push
      php: 7.4
      script:
        - composer coverage
      after_script:
        - composer global require php-coveralls/php-coveralls ^2.1.0
        - ~/.composer/vendor/bin/php-coveralls --verbose --config tests/.coveralls.yml

    - stage: Outdated Dependencies
      if: branch = master AND type = cron
      php: 7.4
      script:
        - composer outdated --direct

  allow_failures:
    - stage: Test Coverage
    - php: nightly

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
